### ISSUE TITLE
Statusline not showing after recent commits

### ISSUE THREAD

**Issue by bigjazzsound** [hardcoreplayers/oceanic-material#16]
Since updated to the latest changes, the statusline is no longer visible for me. If I revert to commit b018fba6a9583502fa389eb860d9bfa4f1754066, the statusline is visible again. 

I'm running NVIM v0.5.0-1ca67a73c on MacOS, statusline is set to the default.

If you need more info, let me know.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/13180077/87371489-80acff00-c553-11ea-9488-d54ec615d80c.png">

**Comment by glepnir** [comment]
Fixed Thanks for report 👍
