### ISSUE TITLE
Something wired for coc-explorer

### ISSUE THREAD

**Issue by duanmuq** [hardcoreplayers/oceanic-material#17]
The cursorline highlight is wired in coc-explorer window. 

I can't find where is my [cursor.
![image](https://github.com/duanmuq/poetry/blob/master/Snipaste_2020-07-25_21-42-19.jpg)

**Comment by glepnir** [comment]
@duanmuq  Do you update the oceanic_material. with the latest version 
![image](https://user-images.githubusercontent.com/41671631/88458534-5814f580-cec1-11ea-8413-b4141027f933.png)

**Comment by duanmuq** [comment]
Yes, I updated to the newest version. 
I also noticed your setting for coc-explorer ""exec 'hi CocExplorerFileDirectory' .s:fg_green ".
But I still can't see my select line in coc-explorer window.
![image](https://github.com/duanmuq/dotfile/blob/master/explorer.jpg)

I change to another colorscheme, it looks ok, so i think the coc-explorer works correct.
![image](https://github.com/duanmuq/dotfile/blob/master/explorer-1.jpg)

**Comment by glepnir** [comment]
Ok  seems like should be change the coc-explorer floatwindow color. because it same as current cursor color

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/88459979-9adbcb00-cecb-11ea-9552-e1cdee3bd1fa.png)
