### ISSUE TITLE
fzf遮挡问题

### ISSUE THREAD

**Issue by Adnios** [hardcoreplayers/oceanic-material#18]
作者，您好。这个主题很棒！但是在使用fzf有点瑕疵。当前行的文件被遮挡了。请问如何解决？
![image](https://user-images.githubusercontent.com/41060790/89649886-112cf400-d8f4-11ea-8134-8828f163bbf2.png)

**Comment by glepnir** [comment]
你可能需要设置fzf的颜色设置。你换其他主题是否有这个？

**Comment by Adnios** [comment]
谢谢，解决了。我把下图中注释掉就正常了
![image](https://user-images.githubusercontent.com/41060790/89651337-5b16d980-d8f6-11ea-9568-619e860a5e40.png)

我之前用gruvbox没有出现过这个。thank you
