### ISSUE TITLE
Coc warning underline color disappear

### ISSUE THREAD

**Issue by ngocthienvnn** [hardcoreplayers/oceanic-material#19]
Thank for creating such an awesome colorscheme, i'm using it for my web development everyday,
just one issue, when using ocean background, the Coc warning underline disappear, could you update the colorscheme or give me any suggestion on how to fix it ? 
![image](https://user-images.githubusercontent.com/14000527/91793393-43571a80-ec42-11ea-960d-9f19deb62bf9.png)

**Comment by glepnir** [comment]
I had add underline for coc warn and error highlight. Please update then enable underline .

**Comment by ngocthienvnn** [comment]
![image](https://user-images.githubusercontent.com/14000527/91795132-0c373800-ec47-11ea-80ca-a157977d7ba0.png)
just update your repo, but i could not see any change? do i miss something ? i tried to change to other colorscheme, and could see the underline, but still not see in this awesome colorscheme.

**Comment by glepnir** [comment]
`let g:oceanic_material_allow_underline = 1`

**Comment by ngocthienvnn** [comment]
Thank so much, it works for Error message now, how about it:
![image](https://user-images.githubusercontent.com/14000527/91796013-5e795880-ec49-11ea-900b-b35f0264e521.png)
Here is message from Coc: Symbol '$sku' is declare but no used. it still not have the underline

**Comment by glepnir** [comment]
Please update and give it test.

**Comment by ngocthienvnn** [comment]
Still not see the underline for your latest update

**Comment by glepnir** [comment]
what dose this command output `hi CocInfoHighlight`

**Comment by ngocthienvnn** [comment]
Here it is
![image](https://user-images.githubusercontent.com/14000527/91796776-35f25e00-ec4b-11ea-94d4-a07fd763675f.png)

**Comment by glepnir** [comment]
update again.

**Comment by ngocthienvnn** [comment]
It's work now, just one more issue(see my screenshot), the preview window should respect the current background color, not sure that issue come from the colorscheme or Coc.
![image](https://user-images.githubusercontent.com/14000527/91797247-4eaf4380-ec4c-11ea-8460-7f50bf9f3cd8.png)

**Comment by glepnir** [comment]
It's `NormalFloat`.  Does is it will looks like easy to see doc if the float background color same as background color? Try this and  give me a look.
`hi NormalFloat guibg=#1b2b34`

**Comment by ngocthienvnn** [comment]
Awesome, it works.
