### ISSUE TITLE
About Copyright

### ISSUE THREAD

**Issue by sainnhe** [hardcoreplayers/oceanic-material#22]
Please add copyright information for my color scheme -- [gruvbox-material](https://github.com/sainnhe/gruvbox-material), since I can see my actual code everywhere, especially in your [earlier commit](https://github.com/glepnir/oceanic-material/commit/6350e95c217c3da9b17eaa310f039c7525c0e174).

I spent a large amount of time in desiging the color palette and optimizing over 50 file types and plugins, that's not an easy job. I don't mind people to use my code, but please don't violate the [license](https://github.com/sainnhe/gruvbox-material/blob/master/LICENSE).

**Comment by glepnir** [comment]
really? I have not referenced gruvbox-matrial? Are there any duplicate colors?
