### ISSUE TITLE
background contrast

### ISSUE THREAD

**Issue by Gako358** [hardcoreplayers/oceanic-material#24]
Hey,

I am using your color scheme, and loving it. However having trouble with setting softer background.
In my vimrc i use: let g:oceanic_material_background="medium"

but still using #1b2b34

Any help would be much appreciated

**Comment by glepnir** [comment]
I can't reproduce with the minial config.  please update and test.
```vim
set rtp+=path/to/oceanic-material
colorscheme oceanic_material
let g:oceanic_material_background="medium"
```
