### ISSUE TITLE
The font remains bold even after setting g:oceanic_material_allow_bold to 0

### ISSUE THREAD

**Issue by obaranek** [hardcoreplayers/oceanic-material#25]

**Comment by glepnir** [comment]
yes, some bold are hardcored.

**Comment by obaranek** [comment]
I've noticed that when i change the colorscheme, the words are not bolded anymore. So i assumed it would be possible in this colorscheme too

**Comment by glepnir** [comment]
I said.. it hardcored in oceanic material. which group that you don't like it's bold?

**Comment by obaranek** [comment]
Sorry I'm not really familiar with how colorscheme plugins work, I thought you meant it's the font itself that's making the words bold. The function names are in bold for example

**Comment by obaranek** [comment]
Anyways, thanks!

**Comment by glepnir** [comment]
Remove bold in default . update .
