### ISSUE TITLE
conceal not working for nested bulletin points at 4th and above levels.

### ISSUE THREAD

**Issue by whytong** [hardcoreplayers/oceanic-material#27]
For the following markdown text:
```
- [google](https://www.google.com)
  - [google](https://www.google.com)
    - [google](https://www.google.com)
      - [google](https://www.google.com)
```
The display is
```
- google
   - google
     - google
       - [google](https://www.google.com)
```
A similar conceal issue is observed when the indentation uses two spaces for each level except in this case it is the  5th level that the conceal is not working.

**Comment by glepnir** [comment]
hmm sry can't reproduce your issue, maybe you should reproduce this issue with a min config. 
![image](https://user-images.githubusercontent.com/41671631/103251596-437ae300-49b4-11eb-878b-cea32bb53dac.png)
