### ISSUE TITLE
Visual selection looks weird.

### ISSUE THREAD

**Issue by jandamm** [hardcoreplayers/oceanic-material#8]
I'm using alacritty and this is what Visual mode looks like with just the theme enabled:
![image](https://user-images.githubusercontent.com/5963139/86178082-07abb180-bb28-11ea-927e-bd144c8cae5f.png)

This is what it looks like without reverse:
![image](https://user-images.githubusercontent.com/5963139/86178128-1b571800-bb28-11ea-995a-6b15d4c13889.png)

This is what I would expect:
![image](https://user-images.githubusercontent.com/5963139/86178153-2742da00-bb28-11ea-8518-0b230dea757b.png)

**Comment by jandamm** [comment]
Also the naming of some of the options is a bit weird.
For example `g:oceanic_material_enable_reverse` must be set to `1` (`true`) in order to be disabled.
I would expect either `g:oceanic_material_disable_reverse` or a default value of `1` and turn reverse off with `0`.
Same goes for `undercurl` and `underline`.

**Comment by jtuz** [comment]
> I'm using alacritty and this is what Visual mode looks like with just the theme enabled:
> ![image](https://user-images.githubusercontent.com/5963139/86178082-07abb180-bb28-11ea-927e-bd144c8cae5f.png)
> 
> This is what it looks like without reverse:
> ![image](https://user-images.githubusercontent.com/5963139/86178128-1b571800-bb28-11ea-995a-6b15d4c13889.png)
> 
> This is what I would expect:
> ![image](https://user-images.githubusercontent.com/5963139/86178153-2742da00-bb28-11ea-8518-0b230dea757b.png)

I have the same issue, but using Kitty terminal emulator

**Comment by glepnir** [comment]
Thanks for report. what about this ?
![image](https://user-images.githubusercontent.com/41671631/86202795-d8cc2480-bb95-11ea-888b-af3985f1e1e1.png)

**Comment by jandamm** [comment]
Looks good now, thanks! :)
