### ISSUE TITLE
Terminal colors no bright black/white

### ISSUE THREAD

**Issue by jandamm** [hardcoreplayers/oceanic-material#9]
In the terminal color 0-7 and 8-15 are identical.
While this is mostly okay for 1-6 and 9-14 the colors 0, 7, 8 and 15 should be different.
0 and 15 are correct.
But 7 should be a darker tint of white. 8 Should be a lighter tint of black.

Check this for reference:
https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit

**Comment by glepnir** [comment]
Please update.

**Comment by jandamm** [comment]
Works much better 👍 
Thank you!
